// <auto-generated />
using System;
using Bilverkstad.Datalager;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bilverkstad.Datalager.Migrations
{
    [DbContext(typeof(BilverkstadContext))]
    [Migration("20240430144400_Bilverkstad-Grupp7")]
    partial class BilverkstadGrupp7
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bilverkstad.Entitetlagret.Anställd", b =>
                {
                    b.Property<int>("AnställningsNummer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnställningsNummer"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Efternamn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Förnamn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lösenord")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AnställningsNummer");

                    b.ToTable("Anställd");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Anställd");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Bilverkstad.Entitetlagret.Fordon", b =>
                {
                    b.Property<string>("RegNr")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Bilmärke")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KundId")
                        .HasColumnType("int");

                    b.Property<string>("Modell")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RegNr");

                    b.HasIndex("KundId");

                    b.ToTable("Fordon");
                });

            modelBuilder.Entity("Bilverkstad.Entitetlagret.Kund", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Efternamn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Epost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Förnamn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gatuadress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ort")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Personnummer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Postnummer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefonnummer")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kund");
                });

            modelBuilder.Entity("Bilverkstad.Entitetlagret.Reparation", b =>
                {
                    b.Property<int>("ReparationsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReparationsId"));

                    b.Property<int?>("Artikelnummer")
                        .HasColumnType("int");

                    b.Property<int>("BokningsId")
                        .HasColumnType("int");

                    b.Property<int?>("MekanikerAnställningsNummer")
                        .HasColumnType("int");

                    b.Property<int>("Reparationsstatus")
                        .HasColumnType("int");

                    b.Property<int>("ReservdelId")
                        .HasColumnType("int");

                    b.Property<string>("Åtgärd")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReparationsId");

                    b.HasIndex("BokningsId");

                    b.HasIndex("MekanikerAnställningsNummer");

                    b.HasIndex("ReservdelId");

                    b.ToTable("Reparation");
                });

            modelBuilder.Entity("Bilverkstad.Entitetlagret.Reservdel", b =>
                {
                    b.Property<int>("Artikelnummer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Artikelnummer"));

                    b.Property<string>("Namn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Pris")
                        .HasColumnType("real");

                    b.HasKey("Artikelnummer");

                    b.ToTable("Reservdel");
                });

            modelBuilder.Entity("Bokning", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BokningStatus")
                        .HasColumnType("int");

                    b.Property<string>("FordonRegNr")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("InlämningsDatum")
                        .HasColumnType("datetime2");

                    b.Property<int>("KundId")
                        .HasColumnType("int");

                    b.Property<int?>("MekanikerId")
                        .HasColumnType("int");

                    b.Property<int>("ReceptionistId")
                        .HasColumnType("int");

                    b.Property<string>("SyfteMedBesök")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UtlämningsDatum")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FordonRegNr");

                    b.HasIndex("KundId");

                    b.HasIndex("MekanikerId");

                    b.HasIndex("ReceptionistId");

                    b.ToTable("Bokning");
                });

            modelBuilder.Entity("Bilverkstad.Entitetlagret.Mekaniker", b =>
                {
                    b.HasBaseType("Bilverkstad.Entitetlagret.Anställd");

                    b.Property<int>("Specialiseringar")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Mekaniker");
                });

            modelBuilder.Entity("Bilverkstad.Entitetlagret.Receptionist", b =>
                {
                    b.HasBaseType("Bilverkstad.Entitetlagret.Anställd");

                    b.Property<int>("Auktoritet")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Receptionist");
                });

            modelBuilder.Entity("Bilverkstad.Entitetlagret.Fordon", b =>
                {
                    b.HasOne("Bilverkstad.Entitetlagret.Kund", "Kund")
                        .WithMany("Fordon")
                        .HasForeignKey("KundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kund");
                });

            modelBuilder.Entity("Bilverkstad.Entitetlagret.Reparation", b =>
                {
                    b.HasOne("Bokning", "Bokning")
                        .WithMany("Reparation")
                        .HasForeignKey("BokningsId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Bilverkstad.Entitetlagret.Mekaniker", "Mekaniker")
                        .WithMany()
                        .HasForeignKey("MekanikerAnställningsNummer");

                    b.HasOne("Bilverkstad.Entitetlagret.Reservdel", "Reservdelar")
                        .WithMany()
                        .HasForeignKey("ReservdelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bokning");

                    b.Navigation("Mekaniker");

                    b.Navigation("Reservdelar");
                });

            modelBuilder.Entity("Bokning", b =>
                {
                    b.HasOne("Bilverkstad.Entitetlagret.Fordon", "Fordon")
                        .WithMany()
                        .HasForeignKey("FordonRegNr")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Bilverkstad.Entitetlagret.Kund", "Kund")
                        .WithMany()
                        .HasForeignKey("KundId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Bilverkstad.Entitetlagret.Mekaniker", "Mekaniker")
                        .WithMany("Bokningar")
                        .HasForeignKey("MekanikerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Bilverkstad.Entitetlagret.Receptionist", "Receptionist")
                        .WithMany()
                        .HasForeignKey("ReceptionistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fordon");

                    b.Navigation("Kund");

                    b.Navigation("Mekaniker");

                    b.Navigation("Receptionist");
                });

            modelBuilder.Entity("Bilverkstad.Entitetlagret.Kund", b =>
                {
                    b.Navigation("Fordon");
                });

            modelBuilder.Entity("Bokning", b =>
                {
                    b.Navigation("Reparation");
                });

            modelBuilder.Entity("Bilverkstad.Entitetlagret.Mekaniker", b =>
                {
                    b.Navigation("Bokningar");
                });
#pragma warning restore 612, 618
        }
    }
}
