// <auto-generated />
using System;
using Bilverkstad.Datalager;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bilverkstad.Datalager.Migrations
{
    [DbContext(typeof(BilverkstadContext))]
    partial class BilverkstadContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bilverkstad.Entitetlagret.Anställd", b =>
                {
                    b.Property<int>("AnställningsNummer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnställningsNummer"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Efternamn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Förnamn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lösenord")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yrkesroll")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AnställningsNummer");

                    b.ToTable("Anställd");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Anställd");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Bilverkstad.Entitetlagret.Fordon", b =>
                {
                    b.Property<string>("RegNr")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Bilmärke")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KundId")
                        .HasColumnType("int");

                    b.Property<string>("Modell")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RegNr");

                    b.HasIndex("KundId");

                    b.ToTable("Fordon");
                });

            modelBuilder.Entity("Bilverkstad.Entitetlagret.Kund", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Efternamn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Epost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Förnamn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gatuadress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ort")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Personnummer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Postnummer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefonnummer")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kund");
                });

            modelBuilder.Entity("Bilverkstad.Entitetlagret.Reparation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BokningId")
                        .HasColumnType("int");

                    b.Property<string>("Åtgärd")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BokningId");

                    b.ToTable("Reparation");
                });

            modelBuilder.Entity("Bilverkstad.Entitetlagret.Reservdel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Namn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Pris")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ReparationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReparationId");

                    b.ToTable("Reservdel");
                });

            modelBuilder.Entity("Bokning", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FordonRegNr")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("InlämningsDatum")
                        .HasColumnType("datetime2");

                    b.Property<int>("KundId")
                        .HasColumnType("int");

                    b.Property<int>("ReceptionistAnställningsNummer")
                        .HasColumnType("int");

                    b.Property<string>("SyfteMedBesök")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UtlämningsDatum")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FordonRegNr");

                    b.HasIndex("KundId");

                    b.HasIndex("ReceptionistAnställningsNummer");

                    b.ToTable("Bokning");
                });

            modelBuilder.Entity("Bilverkstad.Entitetlagret.Mekaniker", b =>
                {
                    b.HasBaseType("Bilverkstad.Entitetlagret.Anställd");

                    b.Property<int>("Specialiseringar")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Mekaniker");
                });

            modelBuilder.Entity("Bilverkstad.Entitetlagret.Receptionist", b =>
                {
                    b.HasBaseType("Bilverkstad.Entitetlagret.Anställd");

                    b.HasDiscriminator().HasValue("Receptionist");
                });

            modelBuilder.Entity("Bilverkstad.Entitetlagret.Fordon", b =>
                {
                    b.HasOne("Bilverkstad.Entitetlagret.Kund", "Kund")
                        .WithMany("Fordon")
                        .HasForeignKey("KundId");

                    b.Navigation("Kund");
                });

            modelBuilder.Entity("Bilverkstad.Entitetlagret.Reparation", b =>
                {
                    b.HasOne("Bokning", "Bokning")
                        .WithMany()
                        .HasForeignKey("BokningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bokning");
                });

            modelBuilder.Entity("Bilverkstad.Entitetlagret.Reservdel", b =>
                {
                    b.HasOne("Bilverkstad.Entitetlagret.Reparation", null)
                        .WithMany("Reservdelar")
                        .HasForeignKey("ReparationId");
                });

            modelBuilder.Entity("Bokning", b =>
                {
                    b.HasOne("Bilverkstad.Entitetlagret.Fordon", "Fordon")
                        .WithMany()
                        .HasForeignKey("FordonRegNr")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bilverkstad.Entitetlagret.Kund", "Kund")
                        .WithMany()
                        .HasForeignKey("KundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bilverkstad.Entitetlagret.Receptionist", "Receptionist")
                        .WithMany()
                        .HasForeignKey("ReceptionistAnställningsNummer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fordon");

                    b.Navigation("Kund");

                    b.Navigation("Receptionist");
                });

            modelBuilder.Entity("Bilverkstad.Entitetlagret.Kund", b =>
                {
                    b.Navigation("Fordon");
                });

            modelBuilder.Entity("Bilverkstad.Entitetlagret.Reparation", b =>
                {
                    b.Navigation("Reservdelar");
                });
#pragma warning restore 612, 618
        }
    }
}
